MCPU/Controllers/Admin/MCPU/ProductionController.cs
using MCPU.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCPU.Controllers.Admin.MCPU
{
    public class ProductionController : AuthController
    {
        string BOM_VIEW = "~/Views/Admin/MCPU/Production/BoM.cshtml";
        string PROCESS_VIEW = "~/Views/Admin/MCPU/Production/Process.cshtml";
        string PROCESSINQUIRY_VIEW = "~/Views/Admin/MCPU/Production/ProcessInquiry.cshtml";
        public ActionResult BoM()
        {
            DataTable dt = Product.GetAll();

            ViewBag.PRDCTS = new SelectList(dt.AsDataView(), "PRO_CODE", "PRO_CODE");

            return View(BOM_VIEW);
        }

        [HttpPost]
        public ActionResult LoadItems(string catg)
        {
            DatabaseHelperClass dbHlpr = new DatabaseHelperClass();
            string qry = "SELECT "
                + " RMT_CODE, RMT_DESC1, RMT_DESC2, RMT_TRKMD, RMT_CATG, RMT_SCATG, "
                + " RMT_UDF1, RMT_UDF2, RMT_UDF3, RMT_UDF4, RMT_UOM, RMT_WT, "
                + " RMT_AVCST, RMT_ALCOD, RMT_STATS, RMT_LNKCD "
                + " FROM INV_MSTR_RWMAT "
                + " ORDER BY RMT_CODE ";
            if (catg == "MISC")
            {
                qry = " SELECT "
                    + " BLG_CODE AS RMT_CODE, BLG_NAME AS RMT_DESC1, BLG_UOM AS RMT_UOM, "
                    + " '' AS RMT_DESC2, '' AS RMT_TRKMD, '' AS RMT_CATG, '' AS RMT_SCATG, "
                    + " '' AS RMT_UDF1, '' AS RMT_UDF2, '' AS RMT_UDF3, '' AS RMT_UDF4, '1' AS RMT_WT, "
                    + " '0.00' AS RMT_AVCST, '' AS RMT_ALCOD, '' AS RMT_STATS, '' AS RMT_LNKCD "
                    + " FROM STP_MSTR_BOMLG ";
            }
            DataTable dt = dbHlpr.FetchData(qry);

            return Json(new { success = true, data = JsonConvert.SerializeObject(dt) });
        }

        [HttpPost]
        public ActionResult GetBomByProductCode(string code)
        {
            DatabaseHelperClass dbHlpr = new DatabaseHelperClass();
            DataTable YldBoMHistDetails = dbHlpr.FetchData("SELECT "
                        + " MBM_KEY, MBM_PROCD, MBM_DESC1, "
                        + " MBM_ITMNO, MBM_ITFLG, MBM_SEQNO, "
                        + " MBM_ENTBY, MBM_ENTDT, MBM_ENTIM, "
                        + " MBM_UPDBY, MBM_LSUPD, MBM_LSUPT, "
                        + " MBM_PSTBY, MBM_PSTDT, MBM_PSTIM "
                        + " FROM BOM_MST_MRNTN "
                        + " WHERE MBM_PROCD = '" + code + "' ");
            if (YldBoMHistDetails.Rows.Count > 0)
            {
                return Json(new
                {
                    success = false,
                    msg = "Attention: BoM already exist and posted."
                });
            }

            DataTable DT_USABLES = new DataTable();
            DataTable DT_INGREDIENTS = new DataTable();
            DataTable DT_MISC = new DataTable();
            DataTable YldBoMTrxDetails = dbHlpr.FetchData("SELECT "
                + " MBM_KEY, MBM_PROCD, MBM_DESC1, "
                + " MBM_ITMNO, MBM_ITFLG, MBM_SEQNO, "
                + " MBM_ENTBY, MBM_ENTDT, MBM_ENTIM, "
                + " MBM_UPDBY, MBM_LSUPD, MBM_LSUPT "
                + " FROM BOM_TRX_MRNTN "
                + " WHERE MBM_PROCD = '" + code + "' ");
            if (YldBoMTrxDetails.Rows.Count > 0)
            {
                DT_USABLES = dbHlpr.FetchData("SELECT "
                            + " MBM_ITMNO AS ITMCOD, RMT_DESC1 AS ITMDESC1, RMT_UOM AS ITMUOM, MBM_FRMLA AS ITMFRMLA "
                            + " FROM BOM_TRX_MRNTN "
                            + " LEFT JOIN INV_MSTR_RWMAT ON MBM_ITMNO = RMT_CODE "
                            + " WHERE MBM_ITFLG = '2' "
                            + " AND MBM_PROCD = '" + code + "' "
                            + " ORDER BY MBM_SEQNO ");
                DT_INGREDIENTS = dbHlpr.FetchData("SELECT "
                            + " MBM_ITMNO AS ITMCOD, RMT_DESC1 AS ITMDESC1, RMT_UOM AS ITMUOM, MBM_FRMLA AS ITMFRMLA "
                            + " FROM BOM_TRX_MRNTN "
                            + " LEFT JOIN INV_MSTR_RWMAT ON MBM_ITMNO = RMT_CODE "
                            + " WHERE MBM_ITFLG = '3' "
                            + " AND MBM_PROCD = '" + code + "' "
                            + " ORDER BY MBM_SEQNO ");
                DT_MISC = dbHlpr.FetchData("SELECT "
                    + " BLG_CODE AS ITMCOD, BLG_NAME AS ITMDESC1, BLG_UOM AS ITMUOM, MBM_FRMLA AS ITMFRMLA "
                    + " FROM BOM_TRX_MRNTN "
                    + " LEFT JOIN STP_MSTR_BOMLG ON MBM_ITMNO = BLG_CODE "
                    + " WHERE MBM_ITFLG = '4' "
                    + " AND MBM_PROCD = '" + code + "' "
                    + " ORDER BY MBM_SEQNO ");
            }

            return Json(new
            {
                success = true,
                umtData = JsonConvert.SerializeObject(DT_USABLES),
                ingData = JsonConvert.SerializeObject(DT_INGREDIENTS),
                mscData = JsonConvert.SerializeObject(DT_MISC)
            });
        }

        [HttpPost]
        public ActionResult SaveBoM(FormCollection form)
        {
            if (form["prod_cd"] == null || form["prod_cd"].ToString().Trim().Length <= 0)
            {
                return Json(new
                {
                    success = false,
                    msg = "Error :: Please select a Processed item to save."
                });
            }

            DatabaseHelperClass dbHlpr = new DatabaseHelperClass();
            DateTime dtNow = DateTime.Now;
            string ItmCode = form["prod_cd"].ToString().Trim();
            dbHlpr.ExecuteNonQuery("DELETE FROM BOM_TRX_MRNTN WHERE MBM_PROCD = '" + ItmCode + "' ");
            string[] DT_USABLES = form["umt_items[]"] == null ? new string[] { } : form["umt_items[]"].Split(',');
            string[] DT_UMFRMLA = form["umt_frmla[]"] == null ? new string[] { } : form["umt_frmla[]"].Split(',');
            string[] DT_INGREDIENTS = form["ing_items[]"] == null ? new string[] { } : form["ing_items[]"].Split(',');
            string[] DT_INGFRMLA = form["ing_frmla[]"] == null ? new string[] { } : form["ing_frmla[]"].Split(',');
            string[] DT_MISC = form["msc_items[]"] == null ? new string[] { } : form["msc_items[]"].Split(',');
            string[] DT_MSCFRMLA = form["msc_frmla[]"] == null ? new string[] { } : form["msc_frmla[]"].Split(',');
            if (DT_USABLES.Length > 0 || DT_INGREDIENTS.Length > 0 || DT_MISC.Length > 0)
            {
                DataTable dt = Product.GetByCode(ItmCode);
                string prodDesc1 = dt.Rows[0]["PRO_DESC1"].ToString();
                // Insert Rows for Meat
                for (int i = 0; i < DT_USABLES.Length; i++)
                {
                    string itemNo = DT_USABLES[i];
                    string ItemTypeFlag = "2";
                    int SeqNo = i + 1;
                    float frmla = 0;
                    try { frmla = float.Parse(DT_UMFRMLA[i].ToString()); }
                    catch { }

                    dbHlpr.ExecuteNonQuery("INSERT INTO BOM_TRX_MRNTN ( "
                        + " MBM_KEY, MBM_PROCD, MBM_DESC1, "
                        + " MBM_ITMNO, MBM_ITFLG, MBM_SEQNO, MBM_FRMLA, "
                        + " MBM_ENTBY, MBM_ENTDT, MBM_ENTIM, "
                        + " MBM_UPDBY, MBM_LSUPD, MBM_LSUPT "
                        + " ) VALUES ( "
                        + " '" + ItmCode + itemNo + "', '" + ItmCode + "', '" + prodDesc1 + "', "
                        + " '" + itemNo + "', '" + ItemTypeFlag + "', '" + SeqNo + "', '" + frmla + "', "
                        + " '" + Session["UserId"] + "', '" + dtNow + "', '" + dtNow + "', "
                        + " '" + Session["UserId"] + "', '" + dtNow + "', '" + dtNow + "' "
                        + " ) ");
                }

                // Insert Rows for Ingredients
                for (int i = 0; i < DT_INGREDIENTS.Length; i++)
                {
                    string itemNo = DT_INGREDIENTS[i].ToString();
                    string ItemTypeFlag = "3";
                    int SeqNo = DT_USABLES.Length + i + 1;
                    float frmla = 0;
                    try { frmla = float.Parse(DT_INGFRMLA[i].ToString()); }
                    catch { }

                    dbHlpr.ExecuteNonQuery("INSERT INTO BOM_TRX_MRNTN ( "
                        + " MBM_KEY, MBM_PROCD, MBM_DESC1, "
                        + " MBM_ITMNO, MBM_ITFLG, MBM_SEQNO, MBM_FRMLA, "
                        + " MBM_ENTBY, MBM_ENTDT, MBM_ENTIM, "
                        + " MBM_UPDBY, MBM_LSUPD, MBM_LSUPT "
                        + " ) VALUES ( "
                        + " '" + ItmCode + itemNo + "', '" + ItmCode + "', '" + prodDesc1 + "', "
                        + " '" + itemNo + "', '" + ItemTypeFlag + "', '" + SeqNo + "', '" + frmla + "', "
                        + " '" + Session["UserId"] + "', '" + dtNow + "', '" + dtNow + "', "
                        + " '" + Session["UserId"] + "', '" + dtNow + "', '" + dtNow + "' "
                        + " ) ");
                }

                // Insert Rows for Misc.
                for (int i = 0; i < DT_MISC.Length; i++)
                {
                    string itemNo = DT_MISC[i].ToString();
                    string ItemTypeFlag = "4";
                    int SeqNo = DT_USABLES.Length + DT_INGREDIENTS.Length + i + 1;
                    float frmla = 0;
                    try { frmla = float.Parse(DT_MSCFRMLA[i].ToString()); }
                    catch { }

                    dbHlpr.ExecuteNonQuery("INSERT INTO BOM_TRX_MRNTN ( "
                        + " MBM_KEY, MBM_PROCD, MBM_DESC1, "
                        + " MBM_ITMNO, MBM_ITFLG, MBM_SEQNO, MBM_FRMLA, "
                        + " MBM_ENTBY, MBM_ENTDT, MBM_ENTIM, "

MCPU/Views/Admin/MCPU/Production/ProcessInquiry.cshtml
@{
    ViewBag.Title = "Production Process";
    Layout = "~/Views/Shared/_SiteAdmin.cshtml";
}

@section headContent {
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.min.css">

    <!-- JS -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.jquery.min.js"></script>
}

<div class="topContentBar">
    <ul>
        <li>
            <asp:LinkButton ID="LinkBtnPDF" OnClick="LinkBtnPDF_Click" runat="server">
                <img src="~/img/FilesIcons/acrobat.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonXLX" OnClick="LinkButtonXLX_Click" runat="server">
                <img src="~/img/FilesIcons/excel.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonXxls" OnClick="LinkButtonXxls_Click" runat="server">
                <img src="~/img/FilesIcons/xlsx.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonRtf" OnClick="LinkButtonRtf_Click" runat="server">
                <img src="~/img/FilesIcons/rtf.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonCvs" OnClick="LinkButtonCvs_Click" runat="server">
                <img src="~/img/FilesIcons/cvs.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonWord" OnClick="LinkButtonRtf_Click" runat="server">
                <img src="~/img/FilesIcons/word.png" />
            </asp:LinkButton>
        </li>

        <li>
            <asp:LinkButton ID="LinkButtonHtml" OnClick="LinkButtonHtml_Click" runat="server">
                <img src="~/img/icons/searchtop.jpg" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton6" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/acrobat.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton7" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/word.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton8" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/excel.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton9" OnClick="LinkButton3_Click" OnClientClick="window.print();" runat="server">
                <img src="~/img/FilesIcons/acrobat.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton10" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/torrent.png" />
            </asp:LinkButton>
        </li>
    </ul>
</div>

<div class="formDiv">
    <div class="formHeaderDiv">
        <h3 style="padding: 5px;">Production Process</h3>
    </div>
</div>
<div class="container-fluid" style="margin-top: 15px;">
    <div class="row">
        <div class="col-md-12" id="errors_container">
            @if (TempData.ContainsKey("msg"))
            {
                <div class="alert @(((Dictionary<string, string>)TempData["msg"]).Keys.First().ToString())">
                    @(((Dictionary<string, string>)TempData["msg"]).Values.First().ToString())
                </div>
            }
            @if (TempData.ContainsKey("lblErrorMessage"))
            {
                <div class="alert @(((Dictionary<string, string>)TempData["lblErrorMessage"]).Keys.First().ToString())">
                    @(((Dictionary<string, string>)TempData["lblErrorMessage"]).Values.First().ToString())
                </div>
            }
        </div>
    </div>


    @* Page Content *@
    <div class="row take-full-height">
        <div class="col-md-12">
            <fieldset style="background: #FFFF00; padding: 10px;">
                <legend style="float: left; margin: 0 0 10px 0;">Product Details</legend>

                <div class="row">
                    <div class="col-md-2 form-group"><strong>Product Code : </strong></div>
                    <div class="col-md-2 form-group">@Html.DropDownList("prod_cd", (IEnumerable<SelectListItem>)ViewBag.PRDCTS, "-- Select --", new { id = "prod_cd", @class = "form-control chosen-select" })</div>
                    <div class="col-md-1 form-group"><strong>Desc 1 : </strong></div>
                    <div class="col-md-2 form-group"><small><span id="lblProdDesc1">-</span></small></div>
                    <div class="col-md-1 form-group"><strong>Desc 2 : </strong></div>
                    <div class="col-md-2 form-group"><small><span id="lblProdDesc2">-</span></small></div>
                    <div class="col-md-1 form-group"><strong>UoM : </strong></div>
                    <div class="col-md-1 form-group"><small><span id="lblProdUom">-</span></small></div>
                </div>
            </fieldset>

        </div>
        <div class="col-md-12">
            <fieldset style="background: #d7d7d7; padding: 10px;">
                <legend style="float: left; margin: 0 0 10px 0;">Production Processes</legend>

                <table id="tbl_processes" class="table table-bordered table-responsive table-condensed table-striped table-fgv">
                    <thead>
                        <tr>
                            <th>Process ID</th>
                            <th>Process #</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Total RM Wt.</th>
                            <th>Week</th>
                            <th>Entered By</th>
                            <th>Entered On</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </fieldset>
        </div>
    </div>

</div>

@section footerContent {
    <script type="text/javascript">
        var tbl_processes = null;
        $(function () {
            $(".chosen-select").chosen({ disable_search_threshold: 10, search_contains: true });

            $('#prod_cd').change(function (e) {
                $('#tbl_processes tbody').html('');
                $('#lblProdDesc1').text('-');
                $('#lblProdDesc2').text('-');
                $('#lblProdUom').text('-');

                var $this = $(this);
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetOpenProcessesByProd", "Production")',
                    data: "code=" + $this.val(),
                    dataType: "json",
                    success: function (json) {
                        if (json.success) {
                            var prod_info = JSON.parse(json.data);
                            var processes_list = JSON.parse(json.processes);
                            if (prod_info.length == 1) {
                                $('#lblProdDesc1').text(prod_info[0].PRO_DESC1);
                                $('#lblProdDesc2').text(prod_info[0].PRO_DESC2);
                                $('#lblProdUom').text(prod_info[0].PRO_UOM);

                                var processesHtml = '';
                                $.each(processes_list, function (ky, vl) {
                                    processesHtml += '<tr>';
                                    processesHtml += '<td>' + vl.MPH_ID + '</td>';
                                    processesHtml += '<td>' + vl.MPH_BCHNO + '</td>';
                                    processesHtml += '<td>' + vl.MPH_SDATE + '</td>';
                                    processesHtml += '<td>' + vl.MPH_STIME + '</td>';
                                    processesHtml += '<td>' + vl.MPH_WTKGS + '</td>';
                                    processesHtml += '<td>' + vl.MPH_WEEK + '</td>';
                                    processesHtml += '<td>' + vl.MPH_ENTBY + '</td>';
                                    processesHtml += '<td>' + vl.MPH_ENTDT + '</td>';
                                    processesHtml += '<td><a class="btn btn-sm btn-warning" href="@Url.Action("Process", "Production")?prod=' + vl.MPH_PROCD + '&prcs=' + vl.MPH_ID + '">View & Edit</a></td>';
                                    processesHtml += '</tr>';
                                });
                                if (tbl_processes != null) {
                                    tbl_processes.destroy();
                                }
                                $('#tbl_processes tbody').html(processesHtml);
                                tbl_processes = $('#tbl_processes').DataTable({
                                    "columnDefs": [{
                                        "targets": 2,
                                        "data": "date",
                                        "render": function (data, type, row, meta) {
                                            try {
                                                var date = new Date(data);
                                                var millisecond = Date.parse(data);
                                                const formattedDate = date.toLocaleDateString('en-GB', {
                                                    day: '2-digit', month: 'short', year: 'numeric'
                                                }).replace(/ /g, '-');
                                                return '<td><span style="display: none;">' + millisecond + '</span>' + formattedDate + '</td>';
                                            } catch (e) {
                                                return data;
                                            }
                                        }
                                    }]
                                });
                            }
                        }
                    },
                    error: function (e, r, r) {
                        console.log(e, r, r);
                    }
                });
            });
        });

    </script>
}