MCPU/Controllers/Admin/Setup/DepartmentsController.cs
using MCPU.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCPU.Controllers.Admin.Setup
{
    public class DepartmentsController : AuthController
    {
        string INDEX_VIEW = "~/Views/Admin/Setup/Departments/Index.cshtml";
        string EDIT_VIEW = "~/Views/Admin/Setup/Departments/Edit.cshtml";
        DatabaseHelperClass dbHlpr = new DatabaseHelperClass();
        //
        // GET: /Setup/
        public ActionResult Index()
        {
            List<DepartmentModel> model = DepartmentModel.GetAll();

            ViewBag.POST_DATA = new FormCollection();
            return View(INDEX_VIEW, model);
        }

        [HttpPost]
        public ActionResult Delete(FormCollection form)
        {
            string deptCode = form["department_code"];
            dbHlpr.ExecuteNonQuery("DELETE FROM STP_MSTR_DEPRT WHERE DPT_CODE = '" + deptCode + "'");

            SetSuccessMessage("Department Deleted Successfully");

            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            ViewBag.AllowCodeEdit = true;
            DepartmentModel model = new DepartmentModel("", "");

            return PartialView(EDIT_VIEW, model);
        }
        public ActionResult Edit(string code)
        {
            ViewBag.AllowCodeEdit = false;

            DepartmentModel model = DepartmentModel.GetByCode(code);

            return PartialView(EDIT_VIEW, model);
        }

        [HttpPost]
        public ActionResult Edit(DepartmentModel dptData)
        {
            if (!TryValidateModel(dptData))
            {
                ViewBag.AllowCodeEdit = dptData.Code == null || dptData.Code.Length <= 0;
                return PartialView(EDIT_VIEW, dptData);
            }

            DepartmentModel myDT = DepartmentModel.GetByCode(dptData.Code);
            if (myDT == null)
            {
                dbHlpr.ExecuteNonQuery("INSERT INTO STP_MSTR_DEPRT (DPT_CODE, DPT_NAME) "
                + " VALUES ('" + dptData.Code + "', '" + dptData.Name + "')");

                SetSuccessMessage("Department Created Successfully");
            }
            else
            {
                dbHlpr.ExecuteNonQuery("UPDATE STP_MSTR_DEPRT SET "
                + " DPT_CODE = '" + dptData.Code + "', "
                + " DPT_NAME = '" + dptData.Name + "' "
                + " WHERE DPT_CODE = '" + dptData.Code + "'");

                SetSuccessMessage("Department Updated Successfully");
            }

            return Json(new { url = Url.Action("Index") });
        }

    }
}

MCPU/Controllers/Admin/Setup/MenuItemsController.cs
using MCPU.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCPU.Controllers.Admin.Setup
{
    public class MenuItemsController : AuthController
    {
        string INDEX_VIEW = "~/Views/Admin/Setup/MenuItems/Index.cshtml";
        string EDIT_VIEW = "~/Views/Admin/Setup/MenuItems/Edit.cshtml";
        DatabaseHelperClass dbHlpr = new DatabaseHelperClass();
        //
        // GET: /Setup/
        public ActionResult Index()
        {
            DataTable dt = dbHlpr.FetchData("SELECT * FROM STP_MNU_PAGES");

            List<MenuItemModel> model = new List<MenuItemModel>();
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                model.Add(new MenuItemModel(
                    (int)dt.Rows[i]["PAG_ID"],
                    dt.Rows[i]["PAG_CODE"].ToString(),
                    dt.Rows[i]["PAG_NAME"].ToString(),
                    dt.Rows[i]["PAG_URL"].ToString(),
                    dt.Rows[i]["PAG_TYPE"].ToString(),
                    (int)dt.Rows[i]["PAG_PARNT"],
                    (int)dt.Rows[i]["PAG_SEQNO"]
                    ));
            }

            ViewBag.POST_DATA = new FormCollection();
            return View(INDEX_VIEW, model);
        }

        [HttpPost]
        public ActionResult Delete(FormCollection form)
        {
            string mnuCode = form["mnupg_code"];
            dbHlpr.ExecuteNonQuery("DELETE FROM STP_MNU_PAGES WHERE PAG_CODE = '" + mnuCode + "'");

            SetSuccessMessage("Menu Page Deleted Successfully");

            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            ViewBag.AllowCodeEdit = true;
            MenuItemModel model = new MenuItemModel();

            LoadParentPages();

            return PartialView(EDIT_VIEW, model);
        }

        public ActionResult Edit(string code)
        {
            ViewBag.AllowCodeEdit = false;

            MenuItemModel model = MenuItemModel.GetByCode(code);

            LoadParentPages();

            return PartialView(EDIT_VIEW, model);
        }

        [HttpPost]
        public ActionResult Edit(MenuItemModel mnuData)
        {
            if (!TryValidateModel(mnuData))
            {
                ViewBag.AllowCodeEdit = mnuData.Code == null || mnuData.Code.Length <= 0;
                LoadParentPages();
                return PartialView(EDIT_VIEW, mnuData);
            }

            if (mnuData.Type.Equals("T") || mnuData.Type.ToString().Substring(0, 1).Equals("T"))
            {
                mnuData.Parent = 0;
            }
            else if (mnuData.Parent == null || mnuData.Parent <= 0)
            {
                ModelState.AddModelError("Parent", "Parent field is required");

                ViewBag.AllowCodeEdit = mnuData.Code == null || mnuData.Code.Length <= 0;
                LoadParentPages();
                return PartialView(EDIT_VIEW, mnuData);
            }

            DataTable myDT = dbHlpr.FetchData("SELECT * FROM STP_MNU_PAGES WHERE PAG_CODE = '" + mnuData.Code + "'");
            if (myDT.Rows.Count <= 0)
            {
                dbHlpr.ExecuteNonQuery("INSERT INTO STP_MNU_PAGES (PAG_CODE, PAG_SEQNO, PAG_NAME, PAG_PARNT, PAG_TYPE, PAG_URL) "
                    + " VALUES ( "
                    + " '" + mnuData.Code + "', "
                    + " '" + mnuData.SeqNo + "', "
                    + " '" + mnuData.Name + "', "
                    + " '" + mnuData.Parent + "', "
                    + " '" + ((char)mnuData.Type).ToString() + "', "
                    + " '" + mnuData.Url + "' "
                    + " )");

                SetSuccessMessage("Menu Page Created Successfully");
            }
            else
            {
                dbHlpr.ExecuteNonQuery("UPDATE STP_MNU_PAGES SET "
                    + " PAG_TYPE = '" + ((char)mnuData.Type).ToString() + "', "
                    + " PAG_SEQNO = '" + mnuData.SeqNo + "', "
                    + " PAG_NAME = '" + mnuData.Name + "', "
                    + " PAG_URL = '" + mnuData.Url + "', "
                    + " PAG_PARNT = '" + mnuData.Parent + "' "
                    + " WHERE PAG_CODE = '" + mnuData.Code + "'");

                SetSuccessMessage("Menu Page Updated Successfully");
            }

            return Json(new { url = Url.Action("Index") });
        }

        [NonAction]
        private void LoadParentPages()
        {
            DataTable dt = dbHlpr.FetchData("SELECT * FROM STP_MNU_PAGES");

            List<MenuItemModel> parentsList = new List<MenuItemModel>();
            // parentsList.Add(new MenuItemModel(0, "", "No Parent", "", "", 0, 0));
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                parentsList.Add(new MenuItemModel(
                    (int)dt.Rows[i]["PAG_ID"],
                    dt.Rows[i]["PAG_CODE"].ToString(),
                    dt.Rows[i]["PAG_NAME"].ToString(),
                    dt.Rows[i]["PAG_URL"].ToString(),
                    dt.Rows[i]["PAG_TYPE"].ToString(),
                    (int)dt.Rows[i]["PAG_PARNT"],
                    (int)dt.Rows[i]["PAG_SEQNO"]
                    ));
            }
            ViewBag.ParentMenuPages = parentsList;
        }

    }
}

MCPU/Controllers/Admin/Setup/MenusController.cs
using MCPU.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCPU.Controllers.Admin.Setup
{
    public class MenusController : AuthController
    {
        string INDEX_VIEW = "~/Views/Admin/Setup/Menus/Index.cshtml";
        string EDIT_VIEW = "~/Views/Admin/Setup/Menus/Edit.cshtml";
        DatabaseHelperClass dbHlpr = new DatabaseHelperClass();
        //
        // GET: /Setup/
        public ActionResult Index()
        {
            List<MenuModel> model = MenuModel.GetAll();

            ViewBag.POST_DATA = new FormCollection();
            return View(INDEX_VIEW, model);
        }

        [HttpPost]
        public ActionResult Delete(FormCollection form)
        {
            string menuCode = form["menu_code"];
            MenuModel.DeleteMenu(menuCode);

            SetSuccessMessage("Menu Deleted Successfully");

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult MenuCodeSelectionChanged(string code)
        {
            MenuModel menuDetails = MenuModel.GetByCode(code);

            List<EasyUiTreeNode> treeData = TreeData(code);

            return Json(new { success = true, data = menuDetails, TreeInfo = treeData });
        }


        public List<EasyUiTreeNode> TreeData(string menuCode)
        {
            List<EasyUiTreeNode> pages = MenuItemModel.GetPagesTree(0);
            if (menuCode.Length == 0)
            {
                return PagesTreeJson(pages, new List<int>());
            }
            else
            {
                List<MenuItemModel> menuInfo = MenuModel.GetPagesByCode(menuCode);
                List<int> pageIds = new List<int>();
                foreach (MenuItemModel mnuInf in menuInfo)
                {
                    pageIds.Add(mnuInf.Id);
                }
                return PagesTreeJson(pages, pageIds);
            }
        }

        private List<EasyUiTreeNode> PagesTreeJson(List<EasyUiTreeNode> pages, List<int> checkedIds)
        {
            List<EasyUiTreeNode> arr = new List<EasyUiTreeNode>();
            foreach (EasyUiTreeNode pg in pages)
            {
                EasyUiTreeNode temp = new EasyUiTreeNode();
                temp.id = pg.id;
                temp.text = "<span style='display: none;'>" + pg.id + "</span>" + pg.text;
                temp.@checked = false;
                if (pg.children.Count > 0)
                {
                    temp.children = PagesTreeJson(pg.children, checkedIds);
                }
                else
                {
                    temp.@checked = checkedIds.Contains(pg.id) ? true : false;
                }
                arr.Add(temp);
            }
            return arr;
        }

        [HttpPost]
        public ActionResult Save(FormCollection form)
        {
            bool validRequest = true;
            if (form["menu_code"].Trim().Length == 0)
            {
                SetFailMessage("Failure:: Menu save failed, Menu Code is required.");
                validRequest = false;
            }
            if (form["menu_name"].Trim().Length == 0)
            {
                SetFailMessage("Failure:: Menu save failed, Menu Name is required.");
                validRequest = false;
            }
            if (form["menu_pages"].Trim().Length == 0)
            {
                SetFailMessage("Failure:: Menu save failed, Menu Pages is required.");
                validRequest = false;
            }

            if (validRequest)
            {
                string menuCode = form["menu_code"];
                string menuName = form["menu_name"];
                string menuPages = form["menu_pages"];

                MenuModel myDT = MenuModel.GetByCode(menuCode);
                if (myDT == null)
                {
                    dbHlpr.ExecuteNonQuery("INSERT INTO STP_USR_MENUS (MNU_CODE, MNU_NAME) "
                    + " VALUES ('" + menuCode + "', '" + menuName + "')");

                    SaveMenuPages(menuCode, menuName, menuPages);

                    SetSuccessMessage("Menu Created Successfully");
                }
                else
                {
                    dbHlpr.ExecuteNonQuery("UPDATE STP_USR_MENUS SET "
                    + " MNU_CODE = '" + menuCode + "', "
                    + " MNU_NAME = '" + menuName + "' "
                    + " WHERE MNU_CODE = '" + menuCode + "'");

                    SaveMenuPages(menuCode, menuName, menuPages);

                    SetSuccessMessage("Menu Updated Successfully");
                }
            }

            return RedirectPermanent(Url.Action("Index"));
        }

        [NonAction]
        private void SaveMenuPages(string code, string name, string pages)
        {
            DataTable mnuData = new DataTable();
            mnuData.Columns.Add("mnuCode");
            mnuData.Columns.Add("mnuName");
            mnuData.Columns.Add("mnuPageId");

            string[] pageIds = pages.Split(',');
            foreach (string pgId in pageIds)
            {
                DataRow mnuEntry = mnuData.NewRow();

                mnuEntry["mnuCode"] = code;
                mnuEntry["mnuName"] = name;
                mnuEntry["mnuPageId"] = pgId;

                mnuData.Rows.Add(mnuEntry);
            }

            MenuModel.AddNewMenu(mnuData);
        }
    }
}

MCPU/Views/Admin/Setup/MenuItems/Edit.cshtml
@model MCPU.Models.MenuItemModel

<div class="modal fade" data-backdrop="false" id="addEditModal" tabindex="-1" role="dialog" aria-labelledby="addEditModalModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        @using (Ajax.BeginForm("Edit", "MenuItems",
    new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnSuccess = "onSuccess", UpdateTargetId = "partial_view_popup" },
    new { @id = "AjaxformId", @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        @if (ViewBag.AllowCodeEdit)
                        {
                            @:Create MenuItem
                        }
                        else
                        {
                            @:Edit MenuItem
                        }
                    </h5>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group row v-center">
                        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EnumDropDownListFor(model => model.Type, "-- Select --", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row v-center">
                        @Html.LabelFor(model => model.SeqNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SeqNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SeqNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row v-center">
                        @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Code, new { htmlAttributes = ViewBag.AllowCodeEdit ? (object)new { @class = "form-control" } : (object)new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row v-center">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row v-center">
                        @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row v-center">
                        @Html.LabelFor(model => model.Parent, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Parent, new SelectList(ViewBag.ParentMenuPages, "Id", "Name"), "-- Select --", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Parent, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Save" />
                </div>
            </div>
        }
    </div>
</div>

<script>
    $('#addEditModal').modal('show');
</script>

MCPU/Views/Admin/Setup/MenuItems/Index.cshtml
@model IEnumerable<MCPU.Models.MenuItemModel>

@{
    ViewBag.Title = "MenuItems";
    Layout = "~/Views/Shared/_SiteAdmin.cshtml";
}


<div class="topContentBar">
    <ul>
        <li>
            <asp:LinkButton ID="LinkBtnPDF" OnClick="LinkBtnPDF_Click" runat="server">
                <img src="~/img/FilesIcons/acrobat.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonXLX" OnClick="LinkButtonXLX_Click" runat="server">
                <img src="~/img/FilesIcons/excel.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonXxls" OnClick="LinkButtonXxls_Click" runat="server">
                <img src="~/img/FilesIcons/xlsx.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonRtf" OnClick="LinkButtonRtf_Click" runat="server">
                <img src="~/img/FilesIcons/rtf.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonCvs" OnClick="LinkButtonCvs_Click" runat="server">
                <img src="~/img/FilesIcons/cvs.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonWord" OnClick="LinkButtonRtf_Click" runat="server">
                <img src="~/img/FilesIcons/word.png" />
            </asp:LinkButton>
        </li>

        <li>
            <asp:LinkButton ID="LinkButtonHtml" OnClick="LinkButtonHtml_Click" runat="server">
                <img src="~/img/icons/searchtop.jpg" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton6" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/acrobat.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton7" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/word.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton8" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/excel.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton9" OnClick="LinkButton3_Click" OnClientClick="window.print();" runat="server">
                <img src="~/img/FilesIcons/acrobat.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton10" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/torrent.png" />
            </asp:LinkButton>
        </li>
    </ul>
</div>

<div class="formDiv">
    <div class="formHeaderDiv">
        <h3 style="padding: 5px;">Menu Page Master</h3>
    </div>
</div>
<div class="container-fluid" style="margin-top: 15px;">
    <div class="row">
        <div class="col-md-12">
            @if (TempData.ContainsKey("msg"))
            {
                <div class="col-md-12">
                    <div class="alert @(((Dictionary<string, string>)TempData["msg"]).Keys.First().ToString())">
                        @(((Dictionary<string, string>)TempData["msg"]).Values.First().ToString())
                    </div>
                </div>
            }
        </div>
        <div class="col-md-12">
            <table id="tbl_mnupgs" class="table table-striped table-hover table-frsn-listing nowrap">
                <thead>
                    <tr>
                        <th width="20%">@Html.DisplayNameFor(model => model.Code)</th>
                        <th width="20%">@Html.DisplayNameFor(model => model.SeqNo)</th>
                        <th width="50%">@Html.DisplayNameFor(model => model.Name)</th>
                        <th width="50%">@Html.DisplayNameFor(model => model.Url)</th>
                        <th width="50%">@Html.DisplayNameFor(model => model.Parent)</th>
                        <th width="50%">@Html.DisplayNameFor(model => model.Type)</th>
                        <th width="30%"></th>
                    </tr>
                </thead>
                <tbody>
                    @{int i = 0;}
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Code)</td>
                            <td>@Html.DisplayFor(modelItem => item.SeqNo)</td>
                            <td>@Html.DisplayFor(modelItem => item.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.Url)</td>
                            <td>@Html.DisplayFor(modelItem => item.Parent)</td>
                            <td>@Html.DisplayFor(modelItem => item.Type)</td>
                            <td>
                                <button id="btn-@i" class="btn btn-sm btn-warning renderaction"
                                        data-actionurl="@Url.Action("Edit", "MenuItems", new { code=item.Code })">
                                    <span class="glyphicon glyphicon-edit"></span>Edit
                                </button>
                                <button class="btn btn-sm btn-danger"
                                        data-backdrop="false" data-toggle="modal" data-target="#deleteModal" data-dismiss="modal"
                                        data-mnupgcode="@Html.DisplayFor(modelItem => item.Code)">
                                    <span class="glyphicon glyphicon-edit"></span>Delete
                                </button>
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
        <div class="col-md-12">
            <button class="btn btn-primary renderaction" data-actionurl="@Url.Action("Create", "MenuItems")">Create New</button>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        @using (Html.BeginForm("Delete", "MenuItems"))
        {
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete MenuItem</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" class="form-control" id="mnupg_code" name="mnupg_code">
                    <div class="form-group">
                        <label for="mnupg_code" class="col-form-label">Are you sure to delete record?</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Confirm</button>
                </div>
            </div>
        }
    </div>
</div>
<div id="partial_view_popup">

</div>

<script type="text/javascript">
    $(function () {
        $('#tbl_mnupgs').DataTable({
            "scrollX": true,
            "colReorder": true
        });
        @{
            if (!ViewData.ModelState.IsValid)
            {
                @:$('.validation-summary-errors').addClass('alert alert-danger');
            }
        }
    });

    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget); // Button that triggered the modal
        var code = button.data('mnupgcode');
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        var modal = $(this);
        modal.find('.modal-body #mnupg_code').val(code);
    });
</script>