MCPU/Controllers/Admin/MCPU/YieldingController.cs
using MCPU.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCPU.Controllers.Admin.MCPU
{
    public class YieldingController : AuthController
    {
        string BOM_VIEW = "~/Views/Admin/MCPU/Yielding/BoM.cshtml";
        string PROCESS_VIEW = "~/Views/Admin/MCPU/Yielding/Process.cshtml";
        string PROCESSINQUIRY_VIEW = "~/Views/Admin/MCPU/Yielding/ProcessInquiry.cshtml";
        public ActionResult BoM()
        {
            DataTable dt = RawMaterial.GetAll();

            ViewBag.RMTS = new SelectList(dt.AsDataView(), "RMT_CODE", "RMT_CODE");

            return View(BOM_VIEW);
        }

        public ActionResult ProcessInquiry()
        {
            DataTable dt = RawMaterial.GetAll();

            ViewBag.RMTS = new SelectList(dt.AsDataView(), "RMT_CODE", "RMT_CODE");

            return View(PROCESSINQUIRY_VIEW);
        }

        public ActionResult Process(string rm, string pr)
        {
            DataTable dt = RawMaterial.GetAll();
            ViewBag.RMTS = new SelectList(dt.AsDataView(), "RMT_CODE", "RMT_CODE");
            ViewBag.UMTS = new SelectList(dt.AsDataView(), "RMT_CODE", "RMT_CODE");

            ViewBag.BatchStartDateEnabled = true;
            ViewBag.BatchStartDate = "";
            ViewBag.BatchEndDate = "";
            ViewBag.BatchStartTime = "";
            ViewBag.BatchEndTime = "";
            ViewBag.ProcessId = "";
            ViewBag.RmCodeReadOnly = false;
            ViewBag.RmCode = "";
            ViewBag.RefNo = "";
            ViewBag.PostEnabled = false;
            if (rm != null && pr != null && rm != "" && pr != "")
            {

                DataTable YieldingDetails = YieldingModel.GetProcessHeader(rm, pr);
                if (YieldingDetails.Rows.Count > 0)
                {
                    ViewBag.RMTS = new SelectList(dt.AsDataView(), "RMT_CODE", "RMT_CODE", rm);
                    ViewBag.RmCode = rm;
                    ViewBag.ProcessId = pr;
                    ViewBag.PostEnabled = true;
                    ViewBag.BatchStartDateEnabled = false;

                    try
                    {
                        ViewBag.BatchStartDate = Convert.ToDateTime(YieldingDetails.Rows[0]["PRH_SDATE"].ToString()).ToString("dd-MMM-yyyy");
                    }
                    catch (Exception ex)
                    {
                        ViewBag.BatchStartDate = "";
                    }

                    try
                    {
                        ViewBag.BatchEndDate = Convert.ToDateTime(YieldingDetails.Rows[0]["PRH_EDATE"].ToString()).ToString("dd-MMM-yyyy");
                    }
                    catch (Exception ex)
                    {
                        ViewBag.BatchEndDate = "";
                    }

                    try
                    {
                        ViewBag.BatchStartTime = Convert.ToDateTime(YieldingDetails.Rows[0]["PRH_STIME"].ToString()).ToString("HH:mm");
                    }
                    catch (Exception ex)
                    {
                        ViewBag.BatchStartTime = "00:00";
                    }

                    try
                    {
                        ViewBag.BatchEndTime = Convert.ToDateTime(YieldingDetails.Rows[0]["PRH_ETIME"].ToString()).ToString("HH:mm");
                    }
                    catch (Exception ex)
                    {
                        ViewBag.BatchEndTime = "00:00";
                    }

                    ViewBag.RmCodeReadOnly = true;
                    ViewBag.RefNo = YieldingDetails.Rows[0]["PRH_REFNO"].ToString();
                }
            }

            return View(PROCESS_VIEW);
        }

        [HttpPost]
        public ActionResult LoadProcess(string code, string prcs, string sndr, bool rmRdOnly)
        {
            if (sndr.ToLower() == "rmt")
            {
                DataTable DT_GRVS = new DataTable();
                DataTable DT_RAWMEAT = new DataTable();
                DataTable DT_USABLES = new DataTable();
                DataTable DT_WASTAGES = new DataTable();

                string desc1 = "";
                string desc2 = "";
                string uom = "";

                string processId = "";
                try
                {
                    processId = YieldingModel.GetNextProcessId(code, Convert.ToDateTime(prcs));
                }
                catch (Exception)
                {
                    processId = prcs;
                }

                if (code != null)
                {
                    DatabaseHelperClass dbHlpr = new DatabaseHelperClass();
                    DataTable dt = dbHlpr.FetchData("SELECT "
                        + " RMT_CODE, RMT_DESC1, RMT_DESC2, RMT_TRKMD, RMT_CATG, RMT_SCATG, "
                        + " RMT_UDF1, RMT_UDF2, RMT_UDF3, RMT_UDF4, RMT_UOM, RMT_WT, "
                        + " RMT_AVCST, RMT_ALCOD, RMT_STATS, RMT_LNKCD "
                        + " FROM INV_MSTR_RWMAT "
                        + " WHERE RMT_CODE = '" + code + "' ");
                    if (dt.Rows.Count > 0)
                    {
                        desc1 = dt.Rows[0]["RMT_DESC1"].ToString();
                        desc2 = dt.Rows[0]["RMT_DESC2"].ToString();
                        uom = dt.Rows[0]["RMT_UOM"].ToString();

                        DT_GRVS = dbHlpr.FetchData("SELECT "
                                + " RCE_KEY, RCE_CPGRV, RCE_RMCOD, RCE_EXPDT "
                                + " FROM INV_GRV_EXPIRY "
                                + " WHERE RCE_RMCOD = '" + dt.Rows[0]["RMT_LNKCD"].ToString() + "' "
                                + " ORDER BY RCE_CPGRV, RCE_EXPDT DESC ");

                        DT_RAWMEAT = dbHlpr.FetchData("SELECT "
                            + " RCE_KEY AS ITMGRV, PRL_QTY AS ITMQTY, "
                            + " PRL_EXPDT AS ITMEXPRY, RCV_REFNO AS ITMREFNO "
                            + " FROM PRC_TRX_YLDLN "
                            + " LEFT JOIN INV_GRV_RCVNG ON RCV_RMCOD = '" + code + "' AND PRL_GRVNO = RCV_CPGRV "
                            + " LEFT JOIN INV_GRV_EXPIRY ON RCE_RMCOD = '" + code + "' AND PRL_GRVNO = RCE_CPGRV AND PRL_EXPDT = RCE_EXPDT "
                            + " WHERE PRL_ID = '" + processId + "' AND PRL_TYPE = 'RMT' ");
                        if (rmRdOnly)
                        {
                            DT_USABLES = dbHlpr.FetchData("SELECT "
                                + " PRL_ITMCD AS ITMCOD, RMT_DESC1 AS ITMDESC1, COALESCE(PRL_QTY, 0.000) AS ITMQTY "
                                + " FROM PRC_TRX_YLDLN "
                                + " LEFT JOIN BOM_MST_YLDNG ON PRL_ITMCD = YBM_ITMNO AND PRL_RMCOD = YBM_RMCOD "
                                + " LEFT JOIN INV_MSTR_RWMAT ON PRL_ITMCD = RMT_CODE "
                                + " WHERE PRL_TYPE = 'UMT' "
                                + " AND PRL_RMCOD = '" + code + "' AND PRL_ID = '" + processId + "' "
                                + " ORDER BY YBM_SEQNO ");
                            DT_WASTAGES = dbHlpr.FetchData("SELECT "
                                + " PRL_ITMCD AS ITMCOD, RMT_DESC1 AS ITMDESC1, COALESCE(PRL_QTY, 0.000) AS ITMQTY "
                                + " FROM PRC_TRX_YLDLN "
                                + " LEFT JOIN BOM_MST_YLDNG ON PRL_ITMCD = YBM_ITMNO AND PRL_RMCOD = YBM_RMCOD "
                                + " LEFT JOIN INV_MSTR_RWMAT ON PRL_ITMCD = RMT_CODE "
                                + " WHERE PRL_TYPE = 'WST' "
                                + " AND PRL_RMCOD = '" + code + "' AND PRL_ID = '" + processId + "' "
                                + " ORDER BY YBM_SEQNO ");
                        }
                        else
                        {
                            DT_USABLES = dbHlpr.FetchData("SELECT "
                                + " YBM_ITMNO AS ITMCOD, RMT_DESC1 AS ITMDESC1, COALESCE(PRL_QTY, 0.000) AS ITMQTY "
                                + " FROM BOM_MST_YLDNG "
                                + " LEFT JOIN INV_MSTR_RWMAT ON YBM_ITMNO = RMT_CODE "
                                + " LEFT JOIN PRC_TRX_YLDLN ON YBM_ITMNO = PRL_ITMCD AND PRL_TYPE = 'UMT' AND PRL_ID = '" + processId + "' "
                                + " WHERE YBM_ITFLG = '2' "
                                + " AND YBM_RMCOD = '" + code + "' "
                                + " ORDER BY YBM_SEQNO ");
                            DT_WASTAGES = dbHlpr.FetchData("SELECT "
                                + " YBM_ITMNO AS ITMCOD, RMT_DESC1 AS ITMDESC1, COALESCE(PRL_QTY, 0.000) AS ITMQTY "
                                + " FROM BOM_MST_YLDNG "
                                + " LEFT JOIN INV_MSTR_RWMAT ON YBM_ITMNO = RMT_CODE "
                                + " LEFT JOIN PRC_TRX_YLDLN ON YBM_ITMNO = PRL_ITMCD AND PRL_TYPE = 'WST' AND PRL_ID = '" + processId + "' "
                                + " WHERE YBM_ITFLG = '3' "
                                + " AND YBM_RMCOD = '" + code + "' "
                                + " ORDER BY YBM_SEQNO ");
                        }

                        return Json(new
                        {
                            success = true,
                            rmData = new { rmCode = code, rmDesc1 = desc1, rmDesc2 = desc2, rmUom = uom },
                            grvsData = JsonConvert.SerializeObject(DT_GRVS),
                            rmTblData = JsonConvert.SerializeObject(DT_RAWMEAT),
                            usTblData = JsonConvert.SerializeObject(DT_USABLES),
                            wsTblData = JsonConvert.SerializeObject(DT_WASTAGES),
                            prcsId = processId
                        });
                    }
                    else
                    {
                        return Json(new
                        {

MCPU/Views/Admin/MCPU/Yielding/ProcessInquiry.cshtml
@{
    ViewBag.Title = "Yielding Process";
    Layout = "~/Views/Shared/_SiteAdmin.cshtml";
}

@section headContent {
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.min.css">

    <!-- JS -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.jquery.min.js"></script>
}

<div class="topContentBar">
    <ul>
        <li>
            <asp:LinkButton ID="LinkBtnPDF" OnClick="LinkBtnPDF_Click" runat="server">
                <img src="~/img/FilesIcons/acrobat.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonXLX" OnClick="LinkButtonXLX_Click" runat="server">
                <img src="~/img/FilesIcons/excel.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonXxls" OnClick="LinkButtonXxls_Click" runat="server">
                <img src="~/img/FilesIcons/xlsx.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonRtf" OnClick="LinkButtonRtf_Click" runat="server">
                <img src="~/img/FilesIcons/rtf.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonCvs" OnClick="LinkButtonCvs_Click" runat="server">
                <img src="~/img/FilesIcons/cvs.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButtonWord" OnClick="LinkButtonRtf_Click" runat="server">
                <img src="~/img/FilesIcons/word.png" />
            </asp:LinkButton>
        </li>

        <li>
            <asp:LinkButton ID="LinkButtonHtml" OnClick="LinkButtonHtml_Click" runat="server">
                <img src="~/img/icons/searchtop.jpg" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton6" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/acrobat.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton7" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/word.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton8" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/excel.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton9" OnClick="LinkButton3_Click" OnClientClick="window.print();" runat="server">
                <img src="~/img/FilesIcons/acrobat.png" />
            </asp:LinkButton>
        </li>
        <li>
            <asp:LinkButton ID="LinkButton10" OnClick="LinkButton3_Click" runat="server">
                <img src="~/img/FilesIcons/torrent.png" />
            </asp:LinkButton>
        </li>
    </ul>
</div>

<div class="formDiv">
    <div class="formHeaderDiv">
        <h3 style="padding: 5px;">Yielding Process</h3>
    </div>
</div>
<div class="container-fluid" style="margin-top: 15px;">
    <div class="row">
        <div class="col-md-12" id="errors_container">
            @if (TempData.ContainsKey("msg"))
            {
                <div class="alert @(((Dictionary<string, string>)TempData["msg"]).Keys.First().ToString())">
                    @(((Dictionary<string, string>)TempData["msg"]).Values.First().ToString())
                </div>
            }
            @if (TempData.ContainsKey("lblErrorMessage"))
            {
                <div class="alert @(((Dictionary<string, string>)TempData["lblErrorMessage"]).Keys.First().ToString())">
                    @(((Dictionary<string, string>)TempData["lblErrorMessage"]).Values.First().ToString())
                </div>
            }
        </div>
    </div>


    @* Page Content *@
    <div class="row take-full-height">
        <div class="col-md-12">
            <fieldset style="background: #FFFF00; padding: 10px;">
                <legend style="float: left; margin: 0 0 10px 0;">Raw Material Details</legend>

                <div class="row">
                    <div class="col-md-1 form-group"><strong>RM Code : </strong></div>
                    <div class="col-md-2 form-group">@Html.DropDownList("rmt_cd", (IEnumerable<SelectListItem>)ViewBag.RMTS, "-- Select --", new { id = "rmt_cd", @class = "form-control chosen-select" })</div>
                    <div class="col-md-1 form-group"><strong>Desc 1 : </strong></div>
                    <div class="col-md-2 form-group"><small><span id="lblRmtDesc1">-</span></small></div>
                    <div class="col-md-1 form-group"><strong>Desc 2 : </strong></div>
                    <div class="col-md-2 form-group"><small><span id="lblRmtDesc2">-</span></small></div>
                    <div class="col-md-1 form-group"><strong>UoM : </strong></div>
                    <div class="col-md-1 form-group"><small><span id="lblRmtUom">-</span></small></div>
                </div>
            </fieldset>

        </div>
        <div class="col-md-12">
            <fieldset style="background: #d7d7d7; padding: 10px;">
                <legend style="float: left; margin: 0 0 10px 0;">Yielding Processes</legend>

                <table id="tbl_processes" class="table table-bordered table-responsive table-condensed table-striped table-fgv">
                    <thead>
                        <tr>
                            <th>Process ID</th>
                            <th>Process #</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Total RM Wt.</th>
                            <th>Ref#</th>
                            <th>Week</th>
                            <th>Entered By</th>
                            <th>Entered On</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </fieldset>
        </div>
    </div>

</div>

@section footerContent {
    <script type="text/javascript">
        var tbl_processes = null;
        $(function () {
            $(".chosen-select").chosen({ disable_search_threshold: 10, search_contains: true });

            $('#rmt_cd').change(function (e) {
                $('#tbl_processes tbody').html('');
                $('#lblRmtDesc1').text('-');
                $('#lblRmtDesc2').text('-');
                $('#lblRmtUom').text('-');

                var $this = $(this);
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetOpenProcessesByRmt", "Yielding")',
                    data: "code=" + $this.val(),
                    dataType: "json",
                    success: function (json) {
                        if (json.success) {
                            var rmt_info = JSON.parse(json.data);
                            var processes_list = JSON.parse(json.processes);
                            if (rmt_info.length == 1) {
                                $('#lblRmtDesc1').text(rmt_info[0].RMT_DESC1);
                                $('#lblRmtDesc2').text(rmt_info[0].RMT_DESC2);
                                $('#lblRmtUom').text(rmt_info[0].RMT_UOM);

                                var processesHtml = '';
                                $.each(processes_list, function (ky, vl) {
                                    processesHtml += '<tr>';
                                    processesHtml += '<td>' + vl.PRH_ID + '</td>';
                                    processesHtml += '<td>' + vl.PRH_BCHNO + '</td>';
                                    processesHtml += '<td>' + vl.PRH_SDATE + '</td>';
                                    processesHtml += '<td>' + vl.PRH_STIME + '</td>';
                                    processesHtml += '<td>' + vl.PRH_WTKGS + '</td>';
                                    processesHtml += '<td>' + vl.PRH_REFNO + '</td>';
                                    processesHtml += '<td>' + vl.PRH_WEEK + '</td>';
                                    processesHtml += '<td>' + vl.PRH_ENTBY + '</td>';
                                    processesHtml += '<td>' + vl.PRH_ENTDT + '</td>';
                                    processesHtml += '<td><a class="btn btn-sm btn-warning" href="@Url.Action("Process", "Yielding")?rm=' + vl.PRH_RMCOD + '&pr=' + vl.PRH_ID + '">View & Edit</a></td>';
                                    processesHtml += '</tr>';
                                });
                                if (tbl_processes != null) {
                                    tbl_processes.destroy();
                                }
                                $('#tbl_processes tbody').html(processesHtml);
                                tbl_processes = $('#tbl_processes').DataTable({
                                    "columnDefs": [{
                                        "targets": 2,
                                        "data": "date",
                                        "render": function (data, type, row, meta) {
                                            try {
                                                var date = new Date(data);
                                                var millisecond = Date.parse(data);
                                                const formattedDate = date.toLocaleDateString('en-GB', {
                                                    day: '2-digit', month: 'short', year: 'numeric'
                                                }).replace(/ /g, '-');
                                                return '<td><span style="display: none;">' + millisecond + '</span>' + formattedDate + '</td>';
                                            } catch (e) {
                                                return data;
                                            }
                                        }
                                    }]
                                });
                            }
                        }
                    },
                    error: function (e, r, r) {
                        console.log(e, r, r);
                    }
                });
            });
        });

    </script>
}